services:
  postgres:
    image: postgres:16.3-alpine
    container_name: postgres
    restart: unless-stopped
    user: "1000:1000"
    env_file:
      - .env
    volumes:
      - /opt/docker/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - common-infra
networks:
  common-infra:
    driver: bridge
    name: common-infra
